apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.pr_name }}
  name: {{ .Values.pr_name }}
  labels:
   prv: {{ .Values.pr_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      prv: {{ .Values.pr_name }}
  template:
    metadata:
      name: {{ .Values.pr_name }}
      labels:
       prv: {{ .Values.pr_name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.pr_name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
