
replicaCount: 1

image:
  repository: str25/argocd-course-webapp
  pullPolicy: IfNotPresent
  pr_name: pr-11

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  pr_name: pr-11
  type: ClusterIP
  port: 80

ingress:
  className: "nginx"
  host: example.com
  pr_name: pr-11
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

